### PR TITLE
Compiler clips >32bit int literals

### LINKED ISSUE #7: isSafeInteger broken
`isSafeInteger 5 == False`
`maxSafeInteger == -1`

but yet
```
> (2^53 - 1)
9007199254740991 : number
```

(running on Windows10 64bit)

### PR DESCRIPTION
**Pull request by zwilias**
When the compiler was compiled for 32 bit archs...

Fixes #7

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Thanks!

File: src/Basics/Extra.elm [hunk 1]
```diff
@@ -54,7 +54,7 @@ smaller than that, and behaviour becomes mathematically unsound.
 -}
 minSafeInteger : number
 minSafeInteger =
-    -9007199254740991
+    - maxSafeInteger
```
Comment (jvoigtlaender) [inline src/Basics/Extra.elm:58]: Hi @zwilias, turns out this line was a syntax error. Had to make [this change](https://github.com/elm-community/basics-extra/commit/c832fc5012800f3f786bb48682abd0e42c081031) before publishing a new version of the package. Just telling you in case you think that line should have been accepted by the compiler as it was in your commit. In that case, maybe open a syntax-related ticket in the compiler repository?

Comment (zwilias) [reply src/Basics/Extra.elm:58]: Oh my, I'm so sorry. Glad you noticed! Disallowing a space for unary negation seems alright to me, and some googling reveals [it was very much intentional](https://groups.google.com/forum/#!topic/elm-discuss/DcvoUKPzM_M). Thanks for the fix, @jvoigtlaender. Reminds me to check if there was ever an issue logged for the integer truncation, tho.
